apiVersion: v1
kind: Pod
metadata:
  name: nginx-tomcat
  namespace: default
spec:
  containers:
  - image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
  - image: tomcat:8.0.53
    imagePullPolicy: Always
    name: webserver
    ports:
    - containerPort: 8080
    resources: {}
