apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary
  labels:
    app: summary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: summary
  template:
    metadata:
      labels:
        app: summary
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: cache-volume
        - mountPath: /etc/nginx/conf.d
          name: config-volume
      - image: k8s.gcr.io/test-webserver:latest
        name: webserver
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: nginx-config
